name: Build and deploy website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.3
    - name: Install NPM packages
      run: npm ci
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Create .env file
      run: |
        touch .env
        echo X_API_KEY=${{ secrets.X_API_KEY }} >> .env
        echo ENDPOINT_URL=${{ secrets.ENDPOINT_URL }} >> .env
    - name: Delete gitignore
      run: |
        rm .gitignore
    - name: Push .env to directory
      run: |
        git config user.email ${{ secrets.EMAIL} }
        git config user.name ${{ secrets.USERNAME }}
        git add .
        git commit -m "environment variables"
    - name: Build website
      run: npm run build --if-present
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build